'use client';
import React, { useEffect, useState } from 'react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { PatientRecord } from './PatientRecordsPage';
import { applyPrintSettings } from '../../../lib/printSettings';
import { printElements } from '../../../lib/printDocument';
import { DEFAULT_DOCTOR_PRINT_SETTINGS, getDoctorPrintSettings, type DoctorPrintSettings } from '../../../lib/doctorPrintSettings';
import QrAttention from '../../components/QrAttention';
import MedicalOrdersPrintPages from '../../components/MedicalOrdersPrintPages';
interface EvolutionPoint { fecha: string; tfg: number; creatinina: number; potasio?: number; hemoglobina?: number; proteinuria?: number; calcio?: number; fosforo?: number; pth?: number; }
interface Props { record: PatientRecord; evolution: EvolutionPoint[]; historyRecords: PatientRecord[]; onClose: () => void; onNewEncounter: (record: PatientRecord) => void; }
interface MedicationView { drug?: string; dose?: string; doseUnit?: string; presentation?: string; code?: string; route?: string; frequency?: string; duration?: string; quantity?: string; notes?: string; }
function value(record: PatientRecord, key: string) { const item = record[key]; return item === undefined || item === null || item === '' ? '—' : String(item); }
function Field({ label, value: text, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={`print-field ${wide ? 'print-field-wide' : ''}`}><dt>{label}</dt><dd>{text || '—'}</dd></div>; }
export default function PatientPreviewModal({ record, evolution, historyRecords, onClose, onNewEncounter }: Props) {
  const [doctor, setDoctor] = useState<DoctorPrintSettings>(DEFAULT_DOCTOR_PRINT_SETTINGS);
  useEffect(() => {
    const load = () => setDoctor(getDoctorPrintSettings());
    load();
    window.addEventListener('nefrohc:settings-updated', load);
    return () => window.removeEventListener('nefrohc:settings-updated', load);
  }, []);
  const timeline = historyRecords.filter((item) => (record.cc && item.cc === record.cc) || (!record.cc && item.nombre === record.nombre)).sort((a, b) => String(b.fecha || '').localeCompare(String(a.fecha || '')));
  const medications = Array.isArray(record.medications) ? record.medications as MedicationView[] : [];
  const alerts = Array.isArray(record.riskAlerts) ? record.riskAlerts as Array<{ category?: string; message?: string }> : [];
  const chart = evolution.map((item) => ({ fecha: item.fecha, tfg: item.tfg, creatinina: item.creatinina }));
  return <div className="patient-preview-overlay" role="dialog" aria-modal="true">
    <div className="patient-preview-toolbar no-print"><strong>Vista completa de la historia clínica</strong><div className="flex gap-2"><button type="button" onClick={() => onNewEncounter(record)} className="px-3 py-2 border border-accent text-accent rounded-lg text-sm font-bold">Nueva atención</button><button type="button" onClick={() => { applyPrintSettings(); printElements('Historia clínica del paciente', ['.print-preview-document']); }} className="px-3 py-2 bg-primary text-white rounded-lg text-sm font-bold">Imprimir historia</button><button type="button" onClick={onClose} className="px-3 py-2 border border-border rounded-lg text-sm font-bold">Cerrar</button></div></div>
    <article className="patient-preview-document print-preview-document">
      <header className="clinical-print-letterhead"><img src="/assets/kidney-stethoscope-logo.svg" alt="NefroHC" /><div><h1>{doctor.name}</h1><p>{doctor.specialty} · RM: {doctor.license}</p><p>Cel: {doctor.phone} · {doctor.city}</p></div><div className="clinical-print-meta"><div className="clinical-print-title-row"><strong>HISTORIA CLÍNICA</strong><QrAttention data={{ patient: value(record, 'nombre'), document: value(record, 'cc'), date: value(record, 'fecha'), diagnosis: value(record, 'cie10'), summary: value(record, 'analisis'), medications: medications.filter((med) => med.drug).map((med) => `${med.drug} · ${med.dose || ''} ${med.doseUnit || ''} · ${med.frequency || ''}`), laboratories: value(record, 'prescription_laboratorios').split(/\n/).filter((item) => item !== '—'), paraclinics: value(record, 'prescription_paraclinicos').split(/\n/).filter((item) => item !== '—'), orders: value(record, 'prescription_ordenes_medicas').split(/\n/).filter((item) => item !== '—') }} label="" /></div><span>HC No. {value(record, 'hcno')}</span><span>{value(record, 'fecha')} {value(record, 'hora') !== '—' ? value(record, 'hora') : ''}</span></div></header>
      <section className="clinical-print-section"><h2>1. Identificación del paciente</h2><dl className="clinical-print-grid"><Field label="Nombre completo" value={value(record, 'nombre')} /><Field label="Documento" value={value(record, 'cc')} /><Field label="Edad" value={`${value(record, 'edad')} años`} /><Field label="Sexo" value={value(record, 'sexo')} /><Field label="Celular" value={value(record, 'cel')} /><Field label="EPS / aseguradora" value={value(record, 'eps')} /><Field label="Ciudad" value={value(record, 'ciudad')} /><Field label="Acompañante" value={value(record, 'acompanante')} /><Field label="Alergias / reacciones adversas" value={value(record, 'allergies')} /></dl></section>
      <section className="clinical-print-section"><h2>2. Línea de atenciones del paciente</h2><div className="clinical-print-timeline">{timeline.length ? timeline.map((item, index) => <div key={item._id} className={`clinical-timeline-item ${index === 0 ? 'is-current' : ''}`}><span className="clinical-timeline-dot" /><div><strong>{item.fecha || 'Fecha pendiente'} · {item.motivo || 'Atención clínica'}</strong><p>{item.cie10 || 'Sin diagnóstico registrado'}{item.tfg ? ` · TFG ${item.tfg}` : ''}{item.kdigo ? ` · ${item.kdigo}` : ''}</p></div></div>) : <p className="clinical-print-paragraph">No hay atenciones anteriores.</p>}</div></section>
      <section className="clinical-print-section"><h2>3. Motivo, enfermedad actual y antecedentes</h2><dl className="clinical-print-grid clinical-print-grid-wide"><Field label="Motivo de consulta" value={value(record, 'motivo')} wide /><Field label="Enfermedad actual" value={value(record, 'enf_actual')} wide /><Field label="Antecedentes nefrológicos / nefrotóxicos" value={value(record, 'nefrotox')} /><Field label="Antecedentes familiares y otros" value={value(record, 'fam')} /></dl></section>
      <section className="clinical-print-section"><h2>4. Datos clínicos y signos vitales</h2><dl className="clinical-print-grid"><Field label="Peso / talla" value={`${value(record, 'peso_val')} kg / ${value(record, 'talla_val')} cm`} /><Field label="IMC" value={value(record, 'imc')} /><Field label="Creatinina" value={`${value(record, 'crea_calc')} mg/dL`} /><Field label="BUN" value={`${value(record, 'bun_calc')} mg/dL`} /><Field label="TA / MAP" value={value(record, 'ta')} /><Field label="FC / FR / Sat O₂" value={value(record, 'fc')} /><Field label="Peso actual" value={value(record, 'peso_act')} /><Field label="Glucometría" value={value(record, 'gluco')} /></dl></section>
      <section className="clinical-print-section"><h2>5. Examen físico, laboratorios y clasificación renal</h2><dl className="clinical-print-grid clinical-print-grid-wide"><Field label="Examen cardio-pulmonar" value={value(record, 'ex_cardio')} /><Field label="Abdomen / PPR / edemas" value={value(record, 'ex_abd')} /><Field label="Laboratorios registrados" value={value(record, 'labs2')} /><Field label="Otros resultados / proteinuria" value={value(record, 'labs4')} /><Field label="TFG CKD-EPI 2021" value={value(record, 'tfg')} /><Field label="Clasificación KDIGO" value={value(record, 'kdigo')} /><Field label="CIE-10" value={value(record, 'cie10')} /></dl></section>
      <section className="clinical-print-section"><h2>6. Análisis y plan médico</h2><dl className="clinical-print-grid clinical-print-grid-wide"><Field label="Análisis e impresión diagnóstica" value={value(record, 'analisis')} wide /><Field label="Plan de laboratorios" value={value(record, 'plan_labs')} /><Field label="Tratamiento farmacológico" value={value(record, 'plan_tto')} /><Field label="Indicaciones adicionales" value={value(record, 'additional_notes')} wide /></dl></section>
      {(medications.length > 0 || value(record, 'prescription_laboratorios') !== '—' || value(record, 'prescription_paraclinicos') !== '—' || value(record, 'prescription_ordenes_medicas') !== '—') && <section className="clinical-print-section"><h2>7. Órdenes médicas vinculadas</h2>{medications.length > 0 && <><h3 className="recipe-print-heading">Medicamentos</h3><table className="clinical-print-table"><thead><tr><th>#</th><th>Medicamento</th><th>Código</th><th>Presentación</th><th>Dosis</th><th>Vía / frecuencia</th><th>Duración</th><th>Cantidad</th><th>Indicaciones</th></tr></thead><tbody>{medications.map((med, index) => <tr key={`${med.drug}-${index}`}><td>{index + 1}</td><td>{med.drug || '—'}</td><td>{med.code || '—'}</td><td>{med.presentation || '—'}</td><td>{med.dose || '—'} {med.doseUnit || ''}</td><td>{med.route || '—'} / {med.frequency || '—'}</td><td>{med.duration || '—'}</td><td>{med.quantity || '—'}</td><td>{med.notes || '—'}</td></tr>)}</tbody></table></>}<div className="clinical-print-grid clinical-print-grid-wide"><Field label="Laboratorios externos" value={value(record, 'prescription_laboratorios')} /><Field label="Paraclínicos / exámenes" value={value(record, 'prescription_paraclinicos')} /><Field label="Órdenes médicas" value={value(record, 'prescription_ordenes_medicas')} /><Field label="Número de orden médica" value={value(record, 'prescription_id')} /></div></section>}
      {alerts.length > 0 && <section className="clinical-print-section"><h2>7. Alertas clínicas</h2><ul className="clinical-print-list">{alerts.map((alert, index) => <li key={`${alert.category}-${index}`}><strong>{alert.category || 'Alerta'}:</strong> {alert.message || '—'}</li>)}</ul></section>}
      {chart.length > 1 && <section className="clinical-print-section preview-evolution-chart"><h2>Evolución de TFG y creatinina</h2><ResponsiveContainer width="100%" height={200}><LineChart data={chart}><XAxis dataKey="fecha" tick={{ fontSize: 9 }} /><YAxis yAxisId="left" tick={{ fontSize: 9 }} /><YAxis yAxisId="right" orientation="right" tick={{ fontSize: 9 }} /><Tooltip /><Line yAxisId="left" type="monotone" dataKey="tfg" stroke="#1976d2" strokeWidth={2} dot /><Line yAxisId="right" type="monotone" dataKey="creatinina" stroke="#d97706" strokeWidth={2} dot /></LineChart></ResponsiveContainer><table className="clinical-print-table"><thead><tr><th>Fecha</th><th>TFG</th><th>Creatinina</th><th>Potasio</th><th>Hb</th><th>Proteinuria</th><th>Ca / P / PTH</th></tr></thead><tbody>{evolution.map((point) => <tr key={point.fecha}><td>{point.fecha}</td><td>{point.tfg || '—'}</td><td>{point.creatinina || '—'}</td><td>{point.potasio || '—'}</td><td>{point.hemoglobina || '—'}</td><td>{point.proteinuria || '—'}</td><td>{point.calcio || '—'} / {point.fosforo || '—'} / {point.pth || '—'}</td></tr>)}</tbody></table></section>}
      <footer className="clinical-print-signature">{doctor.signatureDataUrl ? <img src={doctor.signatureDataUrl} alt="Firma del profesional" /> : <div className="signature-line" />}<strong>{doctor.name}</strong><span>{doctor.specialty} · RM: {doctor.license}</span></footer>
    </article>
    <MedicalOrdersPrintPages patient={value(record, 'nombre')} document={value(record, 'cc')} date={value(record, 'fecha')} diagnosis={value(record, 'cie10')} medications={medications.map((med, index) => ({ id: `${med.drug}-${index}`, drug: med.drug || '', dose: med.dose || '', doseUnit: med.doseUnit || '', quantity: med.quantity || '', route: med.route || '', frequency: med.frequency || '', duration: med.duration || '', notes: med.notes || '', presentation: med.presentation || '', maxDose: '', renalAdjustment: '', nephrotoxic: false, favorite: false, code: med.code || '' }))} laboratories={value(record, 'prescription_laboratorios').split(/\n/).filter((item) => item !== '—')} paraclinics={value(record, 'prescription_paraclinicos').split(/\n/).filter((item) => item !== '—')} orders={value(record, 'prescription_ordenes_medicas').split(/\n/).filter((item) => item !== '—')} />
  </div>;
}
