'use client';
import React, { useEffect, useMemo, useState } from 'react';
import AppLayout from '@/components/AppLayout';
import { Download, History, Search, ShieldCheck } from 'lucide-react';
import { AuditEntry } from '../../lib/localData';

export default function AuditPage() {
  const [entries, setEntries] = useState<AuditEntry[]>([]);
  const [search, setSearch] = useState('');
  useEffect(() => { try { setEntries(JSON.parse(localStorage.getItem('nefro_audit_logs') || '[]')); } catch { setEntries([]); } }, []);
  const filtered = useMemo(() => entries.filter((entry) => `${entry.action} ${entry.entity} ${entry.actor} ${entry.summary}`.toLowerCase().includes(search.toLowerCase())), [entries, search]);
  const exportAudit = () => { const csv = ['Fecha,Acción,Entidad,Usuario,Resumen', ...filtered.map((entry) => [entry.at, entry.action, entry.entity, entry.actor, entry.summary].map((value) => `"${String(value).replace(/"/g, '""')}"`).join(','))].join('\n'); const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'NefroHC_auditoria.csv'; anchor.click(); URL.revokeObjectURL(url); };
  return <AppLayout><div className="min-h-screen bg-background p-4 lg:p-8"><div className="max-w-6xl mx-auto space-y-6"><div className="flex flex-wrap justify-between gap-4"><div><h1 className="text-2xl font-extrabold text-primary">Auditoría de usuarios</h1><p className="text-sm text-muted-foreground mt-1">Registro local de accesos, visualizaciones, guardados, eliminaciones y respaldos.</p></div><button type="button" onClick={exportAudit} className="flex items-center gap-2 px-4 py-2 border border-border rounded-lg text-sm font-bold"><Download size={16} /> Exportar</button></div><div className="bg-card border border-border rounded-xl p-4 flex items-center gap-3"><Search size={16} className="text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar usuario, acción o paciente" className="flex-1 bg-transparent outline-none text-sm" /><span className="text-xs text-muted-foreground">{filtered.length} registros</span></div><div className="bg-card border border-border rounded-xl overflow-hidden"><div className="grid grid-cols-[170px_100px_150px_150px_1fr] gap-3 px-4 py-3 bg-muted text-xs font-bold uppercase text-muted-foreground"><span>Fecha</span><span>Acción</span><span>Entidad</span><span>Usuario</span><span>Detalle</span></div>{filtered.length ? filtered.map((entry) => <div key={entry.id} className="grid grid-cols-[170px_100px_150px_150px_1fr] gap-3 px-4 py-3 border-t border-border text-xs"><span>{new Date(entry.at).toLocaleString('es-CO')}</span><span className="font-bold text-accent">{entry.action}</span><span>{entry.entity}</span><span>{entry.actor}</span><span>{entry.summary}</span></div>) : <div className="p-10 text-center text-sm text-muted-foreground"><ShieldCheck className="mx-auto mb-2 text-accent" size={28} />No hay eventos registrados todavía.</div>}</div><p className="text-xs text-muted-foreground flex items-center gap-2"><History size={14} /> La auditoría se conserva localmente y forma parte de los respaldos automáticos.</p></div></div></AppLayout>;
}
