'use client';
import React, { useEffect, useState } from 'react';
import QrAttention from './QrAttention';
import { Medication } from '../types/hcTypes';
import { DEFAULT_DOCTOR_PRINT_SETTINGS, getDoctorPrintSettings } from '../../lib/doctorPrintSettings';
import type { DoctorPrintSettings } from '../../lib/doctorPrintSettings';
interface Props { patient:string; document:string; date:string; diagnosis?:string; medications:Medication[]; laboratories:string[]; paraclinics:string[]; orders:string[]; }
function Header({title,data,doctor}:{title:string;data:Props;doctor:DoctorPrintSettings}){return <header className="clinical-print-letterhead"><img src="/assets/kidney-stethoscope-logo.svg" alt="NefroHC"/><div><h1>{doctor.name}</h1><p>{doctor.specialty} · RM: {doctor.license}</p><p>{doctor.city} · {doctor.phone}</p></div><div className="clinical-print-meta"><div className="clinical-print-title-row"><strong>{title.toUpperCase()}</strong><QrAttention data={{patient:data.patient,document:data.document,date:data.date,diagnosis:data.diagnosis,summary:`Documento de ${title.toLowerCase()}.`,medications:title==='Medicamentos'?data.medications.map((med)=>`${med.drug} · ${med.dose} ${med.doseUnit} · ${med.frequency}`):[],laboratories:title==='Laboratorios'?data.laboratories:[],paraclinics:title==='Paraclínicos'?data.paraclinics:[],orders:title==='Órdenes médicas'?data.orders:[]}} label=""/></div><span>{data.patient||'—'}</span><span>{data.document||'—'} · {data.date||'—'}</span></div></header>;}
function Page({title,data,doctor,children}:{title:string;data:Props;doctor:DoctorPrintSettings;children:React.ReactNode}){return <article className="orders-print-page"><Header title={title} data={data} doctor={doctor}/><div className="orders-print-content">{children}</div><footer className="clinical-print-signature">{doctor.signatureDataUrl?<img src={doctor.signatureDataUrl} alt="Firma del profesional"/>:<div className="signature-line"/>}<strong>{doctor.name}</strong><span>{doctor.specialty} · RM: {doctor.license}</span></footer></article>;}
export default function MedicalOrdersPrintPages({patient,document,date,diagnosis,medications,laboratories,paraclinics,orders}:Props){const [doctor,setDoctor]=useState<DoctorPrintSettings>(DEFAULT_DOCTOR_PRINT_SETTINGS);useEffect(()=>{const load=()=>setDoctor(getDoctorPrintSettings());load();window.addEventListener('nefrohc:settings-updated',load);return()=>window.removeEventListener('nefrohc:settings-updated',load);},[]);const data={patient,document,date,diagnosis,medications,laboratories,paraclinics,orders};return <div className="medical-orders-print-pages print-only">{medications.length>0&&<Page title="Medicamentos" data={data} doctor={doctor}><h2>Medicamentos formulados</h2><table className="clinical-print-table"><thead><tr><th>#</th><th>Medicamento</th><th>Presentación</th><th>Dosis</th><th>Vía</th><th>Frecuencia</th><th>Duración</th><th>Cantidad</th><th>Indicaciones</th></tr></thead><tbody>{medications.map((med,index)=><tr key={`${med.id}-${index}`}><td>{index+1}</td><td>{med.drug||'—'}</td><td>{med.presentation||'—'}</td><td>{med.dose||'—'} {med.doseUnit||''}</td><td>{med.route||'—'}</td><td>{med.frequency||'—'}</td><td>{med.duration||'—'}</td><td>{med.quantity||'—'}</td><td>{med.notes||'—'}</td></tr>)}</tbody></table></Page>}{laboratories.length>0&&<Page title="Laboratorios" data={data} doctor={doctor}><h2>Laboratorios externos solicitados</h2><ul className="orders-print-list">{laboratories.map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ul></Page>}{paraclinics.length>0&&<Page title="Paraclínicos" data={data} doctor={doctor}><h2>Paraclínicos y exámenes solicitados</h2><ul className="orders-print-list">{paraclinics.map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ul></Page>}{orders.length>0&&<Page title="Órdenes médicas" data={data} doctor={doctor}><h2>Órdenes médicas</h2><ul className="orders-print-list">{orders.map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ul></Page>}</div>;}
